//  改背景

// body
const body = document.body

// 畫面背景
const background_color = document.querySelectorAll('.td_content')

// 時鐘黑邊
const clock_black = document.querySelectorAll(
  `#tr_clock_2 .td_clock_11,
  #tr_clock_2 .td_clock_12,
  #tr_clock_2 .td_clock_19,
  #tr_clock_2 .td_clock_20,
  #tr_clock_3 .td_clock_7,
  #tr_clock_3 .td_clock_8,
  #tr_clock_3 .td_clock_9,
  #tr_clock_3 .td_clock_10,
  #tr_clock_3 .td_clock_11,
  #tr_clock_3 .td_clock_12,
  #tr_clock_3 .td_clock_13,
  #tr_clock_3 .td_clock_18,
  #tr_clock_3 .td_clock_19,
  #tr_clock_3 .td_clock_20,
  #tr_clock_3 .td_clock_21,
  #tr_clock_3 .td_clock_22,
  #tr_clock_3 .td_clock_23,
  #tr_clock_3 .td_clock_24,
  #tr_clock_4 .td_clock_7,
  #tr_clock_4 .td_clock_8,
  #tr_clock_4 .td_clock_9,
  #tr_clock_4 .td_clock_10,
  #tr_clock_4 .td_clock_11,
  #tr_clock_4 .td_clock_12,
  #tr_clock_4 .td_clock_13,
  #tr_clock_4 .td_clock_17,
  #tr_clock_4 .td_clock_18,
  #tr_clock_4 .td_clock_19,
  #tr_clock_4 .td_clock_20,
  #tr_clock_4 .td_clock_21,
  #tr_clock_4 .td_clock_22,
  #tr_clock_4 .td_clock_23,
  #tr_clock_4 .td_clock_24,
  #tr_clock_5 .td_clock_5,
  #tr_clock_5 .td_clock_6,
  #tr_clock_5 .td_clock_25,
  #tr_clock_5 .td_clock_26,
  #tr_clock_6 .td_clock_5,
  #tr_clock_6 .td_clock_6,
  #tr_clock_6 .td_clock_25,
  #tr_clock_6 .td_clock_26,
  #tr_clock_7 .td_clock_4,
  #tr_clock_7 .td_clock_27,
  #tr_clock_8 .td_clock_2,
  #tr_clock_8 .td_clock_3,
  #tr_clock_8 .td_clock_28,
  #tr_clock_8 .td_clock_29,
  #tr_clock_9 .td_clock_2,
  #tr_clock_9 .td_clock_3,
  #tr_clock_9 .td_clock_28,
  #tr_clock_9 .td_clock_29,
  #tr_clock_10 .td_clock_2,
  #tr_clock_10 .td_clock_3,
  #tr_clock_10 .td_clock_28,
  #tr_clock_10 .td_clock_29,
  #tr_clock_11 .td_clock_2,
  #tr_clock_11 .td_clock_3,
  #tr_clock_11 .td_clock_28,
  #tr_clock_11 .td_clock_29,
  #tr_clock_12 .td_clock_2,
  #tr_clock_12 .td_clock_3,
  #tr_clock_12 .td_clock_28,
  #tr_clock_12 .td_clock_29,
  #tr_clock_13 .td_clock_2,
  #tr_clock_13 .td_clock_3,
  #tr_clock_13 .td_clock_28,
  #tr_clock_13 .td_clock_29,
  #tr_clock_14 .td_clock_2,
  #tr_clock_14 .td_clock_3,
  #tr_clock_14 .td_clock_28,
  #tr_clock_14 .td_clock_29,
  #tr_clock_15 .td_clock_2,
  #tr_clock_15 .td_clock_3,
  #tr_clock_15 .td_clock_28,
  #tr_clock_15 .td_clock_29,
  #tr_clock_16 .td_clock_2,
  #tr_clock_16 .td_clock_3,
  #tr_clock_16 .td_clock_28,
  #tr_clock_16 .td_clock_29,
  #tr_clock_17 .td_clock_2,
  #tr_clock_17 .td_clock_3,
  #tr_clock_17 .td_clock_28,
  #tr_clock_17 .td_clock_29,
  #tr_clock_18 .td_clock_2,
  #tr_clock_18 .td_clock_3,
  #tr_clock_18 .td_clock_28,
  #tr_clock_18 .td_clock_29,
  #tr_clock_19 .td_clock_2,
  #tr_clock_19 .td_clock_3,
  #tr_clock_19 .td_clock_28,
  #tr_clock_19 .td_clock_29,
  #tr_clock_20 .td_clock_2,
  #tr_clock_20 .td_clock_3,
  #tr_clock_20 .td_clock_28,
  #tr_clock_20 .td_clock_29,
  #tr_clock_21 .td_clock_2,
  #tr_clock_21 .td_clock_3,
  #tr_clock_21 .td_clock_28,
  #tr_clock_21 .td_clock_29,
  #tr_clock_22 .td_clock_2,
  #tr_clock_22 .td_clock_3,
  #tr_clock_22 .td_clock_28,
  #tr_clock_22 .td_clock_29,
  #tr_clock_23 .td_clock_2,
  #tr_clock_23 .td_clock_3,
  #tr_clock_23 .td_clock_28,
  #tr_clock_23 .td_clock_29,
  #tr_clock_24 .td_clock_2,
  #tr_clock_24 .td_clock_3,
  #tr_clock_24 .td_clock_28,
  #tr_clock_24 .td_clock_29,
  #tr_clock_25 .td_clock_4,
  #tr_clock_25 .td_clock_27,
  #tr_clock_26 .td_clock_4,
  #tr_clock_26 .td_clock_27,
  #tr_clock_27 .td_clock_5,
  #tr_clock_27 .td_clock_6,
  #tr_clock_27 .td_clock_25,
  #tr_clock_27 .td_clock_26,
  #tr_clock_28 .td_clock_7,
  #tr_clock_28 .td_clock_8,
  #tr_clock_28 .td_clock_9,
  #tr_clock_28 .td_clock_10,
  #tr_clock_28 .td_clock_11,
  #tr_clock_28 .td_clock_12,
  #tr_clock_28 .td_clock_13,
  #tr_clock_28 .td_clock_14,
  #tr_clock_28 .td_clock_15,
  #tr_clock_28 .td_clock_16,
  #tr_clock_28 .td_clock_17,
  #tr_clock_28 .td_clock_18,
  #tr_clock_28 .td_clock_19,
  #tr_clock_28 .td_clock_20,
  #tr_clock_28 .td_clock_21,
  #tr_clock_28 .td_clock_22,
  #tr_clock_28 .td_clock_23,
  #tr_clock_28 .td_clock_24,
  #tr_clock_29 .td_clock_7,
  #tr_clock_29 .td_clock_8,
  #tr_clock_29 .td_clock_9,
  #tr_clock_29 .td_clock_10,
  #tr_clock_29 .td_clock_11,
  #tr_clock_29 .td_clock_12,
  #tr_clock_29 .td_clock_13,
  #tr_clock_29 .td_clock_14,
  #tr_clock_29 .td_clock_15,
  #tr_clock_29 .td_clock_16,
  #tr_clock_29 .td_clock_17,
  #tr_clock_29 .td_clock_18,
  #tr_clock_29 .td_clock_19,
  #tr_clock_29 .td_clock_20,
  #tr_clock_29 .td_clock_21,
  #tr_clock_29 .td_clock_22,
  #tr_clock_29 .td_clock_23,
  #tr_clock_29 .td_clock_24`
)

//  時鐘本體紅色
const clock_red = document.querySelectorAll(
  `#tr_clock_2 .td_clock_13,
  #tr_clock_2 .td_clock_14,
  #tr_clock_2 .td_clock_15,
  #tr_clock_2 .td_clock_18,
  #tr_clock_2 .td_clock_19,
  #tr_clock_3 .td_clock_14,
  #tr_clock_3 .td_clock_15,
  #tr_clock_4 .td_clock_14,
  #tr_clock_4 .td_clock_15,
  #tr_clock_4 .td_clock_16,
  #tr_clock_5 .td_clock_7,
  #tr_clock_5 .td_clock_8,
  #tr_clock_5 .td_clock_9,
  #tr_clock_5 .td_clock_10,
  #tr_clock_5 .td_clock_11,
  #tr_clock_5 .td_clock_12,
  #tr_clock_5 .td_clock_13,
  #tr_clock_5 .td_clock_14,
  #tr_clock_5 .td_clock_15,
  #tr_clock_5 .td_clock_16,
  #tr_clock_5 .td_clock_17,
  #tr_clock_5 .td_clock_18,
  #tr_clock_5 .td_clock_19,
  #tr_clock_5 .td_clock_20,
  #tr_clock_5 .td_clock_21,
  #tr_clock_5 .td_clock_22,
  #tr_clock_5 .td_clock_23,
  #tr_clock_5 .td_clock_24,
  #tr_clock_6 .td_clock_7,
  #tr_clock_6 .td_clock_8,
  #tr_clock_6 .td_clock_9,
  #tr_clock_6 .td_clock_24,
  #tr_clock_6 .td_clock_25,
  #tr_clock_6 .td_clock_26,
  #tr_clock_7 .td_clock_5,
  #tr_clock_7 .td_clock_6,
  #tr_clock_7 .td_clock_8,
  #tr_clock_7 .td_clock_9,
  #tr_clock_7 .td_clock_24,
  #tr_clock_7 .td_clock_25,
  #tr_clock_7 .td_clock_26,
  #tr_clock_8 .td_clock_4,
  #tr_clock_8 .td_clock_7,
  #tr_clock_8 .td_clock_25,
  #tr_clock_8 .td_clock_26,
  #tr_clock_8 .td_clock_27,
  #tr_clock_9 .td_clock_4,
  #tr_clock_9 .td_clock_7,
  #tr_clock_9 .td_clock_25,
  #tr_clock_9 .td_clock_26,
  #tr_clock_9 .td_clock_27,
  #tr_clock_10 .td_clock_5,
  #tr_clock_10 .td_clock_6,
  #tr_clock_10 .td_clock_27,
  #tr_clock_11 .td_clock_5,
  #tr_clock_11 .td_clock_6,
  #tr_clock_11 .td_clock_27,
  #tr_clock_12 .td_clock_5,
  #tr_clock_12 .td_clock_6,
  #tr_clock_12 .td_clock_27,
  #tr_clock_13 .td_clock_5,
  #tr_clock_13 .td_clock_6,
  #tr_clock_13 .td_clock_27,
  #tr_clock_14 .td_clock_4,
  #tr_clock_14 .td_clock_5,
  #tr_clock_14 .td_clock_6,
  #tr_clock_14 .td_clock_27,
  #tr_clock_15 .td_clock_4,
  #tr_clock_15 .td_clock_5,
  #tr_clock_15 .td_clock_6,
  #tr_clock_15 .td_clock_27,
  #tr_clock_16 .td_clock_4,
  #tr_clock_16 .td_clock_5,
  #tr_clock_16 .td_clock_6,
  #tr_clock_16 .td_clock_27,
  #tr_clock_17 .td_clock_4,
  #tr_clock_17 .td_clock_5,
  #tr_clock_17 .td_clock_6,
  #tr_clock_17 .td_clock_27,
  #tr_clock_18 .td_clock_4,
  #tr_clock_18 .td_clock_5,
  #tr_clock_18 .td_clock_6,
  #tr_clock_18 .td_clock_27,
  #tr_clock_19 .td_clock_4,
  #tr_clock_19 .td_clock_5,
  #tr_clock_19 .td_clock_6,
  #tr_clock_19 .td_clock_27,
  #tr_clock_20 .td_clock_4,
  #tr_clock_20 .td_clock_5,
  #tr_clock_20 .td_clock_6,
  #tr_clock_20 .td_clock_27,
  #tr_clock_21 .td_clock_4,
  #tr_clock_21 .td_clock_5,
  #tr_clock_21 .td_clock_6,
  #tr_clock_21 .td_clock_27,
  #tr_clock_22 .td_clock_4,
  #tr_clock_22 .td_clock_5,
  #tr_clock_22 .td_clock_6,
  #tr_clock_22 .td_clock_27,
  #tr_clock_23 .td_clock_4,
  #tr_clock_23 .td_clock_5,
  #tr_clock_23 .td_clock_6,
  #tr_clock_23 .td_clock_27,
  #tr_clock_24 .td_clock_4,
  #tr_clock_24 .td_clock_5,
  #tr_clock_24 .td_clock_6,
  #tr_clock_24 .td_clock_7,
  #tr_clock_24 .td_clock_25,
  #tr_clock_24 .td_clock_26,
  #tr_clock_24 .td_clock_27,
  #tr_clock_24 .td_clock_4,
  #tr_clock_24 .td_clock_5,
  #tr_clock_24 .td_clock_6,
  #tr_clock_24 .td_clock_7,
  #tr_clock_24 .td_clock_26,
  #tr_clock_25 .td_clock_5,
  #tr_clock_25 .td_clock_6,
  #tr_clock_25 .td_clock_7,
  #tr_clock_25 .td_clock_8,
  #tr_clock_25 .td_clock_9,
  #tr_clock_25 .td_clock_24,
  #tr_clock_25 .td_clock_25,
  #tr_clock_25 .td_clock_26,
  #tr_clock_26 .td_clock_5,
  #tr_clock_26 .td_clock_6,
  #tr_clock_26 .td_clock_7,
  #tr_clock_26 .td_clock_8,
  #tr_clock_26 .td_clock_9,
  #tr_clock_26 .td_clock_24,
  #tr_clock_26 .td_clock_25,
  #tr_clock_26 .td_clock_26,
  #tr_clock_27 .td_clock_7,
  #tr_clock_27 .td_clock_8,
  #tr_clock_27 .td_clock_9,
  #tr_clock_27 .td_clock_10,
  #tr_clock_27 .td_clock_11,
  #tr_clock_27 .td_clock_12,
  #tr_clock_27 .td_clock_13,
  #tr_clock_27 .td_clock_14,
  #tr_clock_27 .td_clock_15,
  #tr_clock_27 .td_clock_16,
  #tr_clock_27 .td_clock_17,
  #tr_clock_27 .td_clock_18,
  #tr_clock_27 .td_clock_19,
  #tr_clock_27 .td_clock_20,
  #tr_clock_27 .td_clock_21,
  #tr_clock_27 .td_clock_22,
  #tr_clock_27 .td_clock_23,
  #tr_clock_27 .td_clock_24`
)

//  時鐘反光黃
const clock_yellow = document.querySelectorAll(`
#tr_clock_2 .td_clock_16,
#tr_clock_2 .td_clock_17,
#tr_clock_3 .td_clock_16,
#tr_clock_3 .td_clock_17,
#tr_clock_7 .td_clock_7,
#tr_clock_8 .td_clock_5,
#tr_clock_8 .td_clock_6,
#tr_clock_9 .td_clock_5,
#tr_clock_9 .td_clock_6,
#tr_clock_10 .td_clock_4,
#tr_clock_11 .td_clock_4,
#tr_clock_12 .td_clock_4,
#tr_clock_13 .td_clock_4`)

//  時鐘中間白
const clock_white = document.querySelectorAll(
  `#tr_clock_8 .td_clock_10,
  #tr_clock_8 .td_clock_13,
  #tr_clock_8 .td_clock_14,
  #tr_clock_8 .td_clock_15,
  #tr_clock_8 .td_clock_17,
  #tr_clock_8 .td_clock_18,
  #tr_clock_8 .td_clock_19,
  #tr_clock_8 .td_clock_22,
  #tr_clock_9 .td_clock_10,
  #tr_clock_9 .td_clock_13,
  #tr_clock_9 .td_clock_14,
  #tr_clock_9 .td_clock_15,
  #tr_clock_9 .td_clock_16,
  #tr_clock_9 .td_clock_17,
  #tr_clock_9 .td_clock_18,
  #tr_clock_9 .td_clock_19,
  #tr_clock_9 .td_clock_22,
  #tr_clock_10 .td_clock_8,
  #tr_clock_10 .td_clock_9,
  #tr_clock_10 .td_clock_10,
  #tr_clock_10 .td_clock_11,
  #tr_clock_10 .td_clock_12,
  #tr_clock_10 .td_clock_13,
  #tr_clock_10 .td_clock_14,
  #tr_clock_10 .td_clock_15,
  #tr_clock_10 .td_clock_16,
  #tr_clock_10 .td_clock_17,
  #tr_clock_10 .td_clock_18,
  #tr_clock_10 .td_clock_19,
  #tr_clock_10 .td_clock_20,
  #tr_clock_10 .td_clock_21,
  #tr_clock_10 .td_clock_22,
  #tr_clock_10 .td_clock_23,
  #tr_clock_10 .td_clock_24,
  #tr_clock_11 .td_clock_10,
  #tr_clock_11 .td_clock_11,
  #tr_clock_11 .td_clock_12,
  #tr_clock_11 .td_clock_13,
  #tr_clock_11 .td_clock_14,
  #tr_clock_11 .td_clock_15,
  #tr_clock_11 .td_clock_16,
  #tr_clock_11 .td_clock_17,
  #tr_clock_11 .td_clock_18,
  #tr_clock_11 .td_clock_19,
  #tr_clock_11 .td_clock_20,
  #tr_clock_11 .td_clock_21,
  #tr_clock_11 .td_clock_22,
  #tr_clock_12 .td_clock_10,
  #tr_clock_12 .td_clock_11,
  #tr_clock_12 .td_clock_12,
  #tr_clock_12 .td_clock_13,
  #tr_clock_12 .td_clock_14,
  #tr_clock_12 .td_clock_15,
  #tr_clock_12 .td_clock_16,
  #tr_clock_12 .td_clock_17,
  #tr_clock_12 .td_clock_18,
  #tr_clock_12 .td_clock_19,
  #tr_clock_12 .td_clock_20,
  #tr_clock_12 .td_clock_21,
  #tr_clock_12 .td_clock_22,
  #tr_clock_13 .td_clock_8,
  #tr_clock_13 .td_clock_9,
  #tr_clock_13 .td_clock_10,
  #tr_clock_13 .td_clock_11,
  #tr_clock_13 .td_clock_12,
  #tr_clock_13 .td_clock_13,
  #tr_clock_13 .td_clock_14,
  #tr_clock_13 .td_clock_15,
  #tr_clock_13 .td_clock_16,
  #tr_clock_13 .td_clock_17,
  #tr_clock_13 .td_clock_18,
  #tr_clock_13 .td_clock_19,
  #tr_clock_13 .td_clock_20,
  #tr_clock_13 .td_clock_21,
  #tr_clock_13 .td_clock_22,
  #tr_clock_13 .td_clock_23,
  #tr_clock_13 .td_clock_24,
  #tr_clock_14 .td_clock_8,
  #tr_clock_14 .td_clock_9,
  #tr_clock_14 .td_clock_10,
  #tr_clock_14 .td_clock_11,
  #tr_clock_14 .td_clock_12,
  #tr_clock_14 .td_clock_13,
  #tr_clock_14 .td_clock_14,
  #tr_clock_14 .td_clock_15,
  #tr_clock_14 .td_clock_16,
  #tr_clock_14 .td_clock_17,
  #tr_clock_14 .td_clock_18,
  #tr_clock_14 .td_clock_19,
  #tr_clock_14 .td_clock_20,
  #tr_clock_14 .td_clock_21,
  #tr_clock_14 .td_clock_22,
  #tr_clock_14 .td_clock_23,
  #tr_clock_14 .td_clock_24,
  #tr_clock_15 .td_clock_8,
  #tr_clock_15 .td_clock_9,
  #tr_clock_15 .td_clock_10,
  #tr_clock_15 .td_clock_11,
  #tr_clock_15 .td_clock_12,
  #tr_clock_15 .td_clock_13,
  #tr_clock_15 .td_clock_14,
  #tr_clock_15 .td_clock_15,
  #tr_clock_15 .td_clock_16,
  #tr_clock_15 .td_clock_17,
  #tr_clock_15 .td_clock_18,
  #tr_clock_15 .td_clock_19,
  #tr_clock_15 .td_clock_20,
  #tr_clock_15 .td_clock_21,
  #tr_clock_15 .td_clock_22,
  #tr_clock_15 .td_clock_23,
  #tr_clock_15 .td_clock_24,
  #tr_clock_16 .td_clock_10,
  #tr_clock_16 .td_clock_11,
  #tr_clock_16 .td_clock_12,
  #tr_clock_16 .td_clock_13,
  #tr_clock_16 .td_clock_14,
  #tr_clock_16 .td_clock_15,
  #tr_clock_16 .td_clock_16,
  #tr_clock_16 .td_clock_17,
  #tr_clock_16 .td_clock_18,
  #tr_clock_16 .td_clock_19,
  #tr_clock_16 .td_clock_20,
  #tr_clock_16 .td_clock_21,
  #tr_clock_16 .td_clock_22,
  #tr_clock_17 .td_clock_10,
  #tr_clock_17 .td_clock_11,
  #tr_clock_17 .td_clock_12,
  #tr_clock_17 .td_clock_13,
  #tr_clock_17 .td_clock_14,
  #tr_clock_17 .td_clock_15,
  #tr_clock_17 .td_clock_16,
  #tr_clock_17 .td_clock_17,
  #tr_clock_17 .td_clock_18,
  #tr_clock_17 .td_clock_19,
  #tr_clock_17 .td_clock_20,
  #tr_clock_17 .td_clock_21,
  #tr_clock_17 .td_clock_22,
  #tr_clock_18 .td_clock_8,
  #tr_clock_18 .td_clock_9,
  #tr_clock_18 .td_clock_10,
  #tr_clock_18 .td_clock_11,
  #tr_clock_18 .td_clock_12,
  #tr_clock_18 .td_clock_13,
  #tr_clock_18 .td_clock_14,
  #tr_clock_18 .td_clock_15,
  #tr_clock_18 .td_clock_16,
  #tr_clock_18 .td_clock_17,
  #tr_clock_18 .td_clock_18,
  #tr_clock_18 .td_clock_19,
  #tr_clock_18 .td_clock_20,
  #tr_clock_18 .td_clock_21,
  #tr_clock_18 .td_clock_22,
  #tr_clock_18 .td_clock_23,
  #tr_clock_18 .td_clock_24,
  #tr_clock_19 .td_clock_8,
  #tr_clock_19 .td_clock_9,
  #tr_clock_19 .td_clock_10,
  #tr_clock_19 .td_clock_11,
  #tr_clock_19 .td_clock_12,
  #tr_clock_19 .td_clock_13,
  #tr_clock_19 .td_clock_14,
  #tr_clock_19 .td_clock_15,
  #tr_clock_19 .td_clock_16,
  #tr_clock_19 .td_clock_17,
  #tr_clock_19 .td_clock_18,
  #tr_clock_19 .td_clock_19,
  #tr_clock_19 .td_clock_20,
  #tr_clock_19 .td_clock_21,
  #tr_clock_19 .td_clock_22,
  #tr_clock_19 .td_clock_23,
  #tr_clock_19 .td_clock_24,
  #tr_clock_20 .td_clock_10,
  #tr_clock_20 .td_clock_11,
  #tr_clock_20 .td_clock_12,
  #tr_clock_20 .td_clock_13,
  #tr_clock_20 .td_clock_14,
  #tr_clock_20 .td_clock_15,
  #tr_clock_20 .td_clock_16,
  #tr_clock_20 .td_clock_17,
  #tr_clock_20 .td_clock_18,
  #tr_clock_20 .td_clock_19,
  #tr_clock_20 .td_clock_20,
  #tr_clock_20 .td_clock_21,
  #tr_clock_20 .td_clock_22,
  #tr_clock_21 .td_clock_10,
  #tr_clock_21 .td_clock_11,
  #tr_clock_21 .td_clock_12,
  #tr_clock_21 .td_clock_13,
  #tr_clock_21 .td_clock_14,
  #tr_clock_21 .td_clock_15,
  #tr_clock_21 .td_clock_16,
  #tr_clock_21 .td_clock_17,
  #tr_clock_21 .td_clock_18,
  #tr_clock_21 .td_clock_19,
  #tr_clock_21 .td_clock_20,
  #tr_clock_21 .td_clock_21,
  #tr_clock_21 .td_clock_22,
  #tr_clock_22 .td_clock_8,
  #tr_clock_22 .td_clock_9,
  #tr_clock_22 .td_clock_10,
  #tr_clock_22 .td_clock_11,
  #tr_clock_22 .td_clock_12,
  #tr_clock_22 .td_clock_13,
  #tr_clock_22 .td_clock_14,
  #tr_clock_22 .td_clock_15,
  #tr_clock_22 .td_clock_16,
  #tr_clock_22 .td_clock_17,
  #tr_clock_22 .td_clock_18,
  #tr_clock_22 .td_clock_19,
  #tr_clock_22 .td_clock_20,
  #tr_clock_22 .td_clock_21,
  #tr_clock_22 .td_clock_22,
  #tr_clock_22 .td_clock_23,
  #tr_clock_22 .td_clock_24,
  #tr_clock_23 .td_clock_8,
  #tr_clock_23 .td_clock_9,
  #tr_clock_23 .td_clock_10,
  #tr_clock_23 .td_clock_11,
  #tr_clock_23 .td_clock_12,
  #tr_clock_23 .td_clock_13,
  #tr_clock_23 .td_clock_14,
  #tr_clock_23 .td_clock_15,
  #tr_clock_23 .td_clock_16,
  #tr_clock_23 .td_clock_17,
  #tr_clock_23 .td_clock_18,
  #tr_clock_23 .td_clock_19,
  #tr_clock_23 .td_clock_20,
  #tr_clock_23 .td_clock_21,
  #tr_clock_23 .td_clock_22,
  #tr_clock_23 .td_clock_23,
  #tr_clock_23 .td_clock_24,
  #tr_clock_24 .td_clock_10,
  #tr_clock_24 .td_clock_13,
  #tr_clock_24 .td_clock_14,
  #tr_clock_24 .td_clock_15,
  #tr_clock_24 .td_clock_17,
  #tr_clock_24 .td_clock_18,
  #tr_clock_24 .td_clock_19,
  #tr_clock_24 .td_clock_22,
  #tr_clock_24 .td_clock_23,
  #tr_clock_24 .td_clock_24`
)

// 時鐘綠
const clock_green = document.querySelectorAll(
  `#tr_clock_6 .td_clock_10,
  #tr_clock_6 .td_clock_11,
  #tr_clock_6 .td_clock_12,
  #tr_clock_6 .td_clock_13,
  #tr_clock_6 .td_clock_14,
  #tr_clock_6 .td_clock_15,
  #tr_clock_6 .td_clock_16,
  #tr_clock_6 .td_clock_17,
  #tr_clock_6 .td_clock_18,
  #tr_clock_6 .td_clock_19,
  #tr_clock_6 .td_clock_20,
  #tr_clock_6 .td_clock_21,
  #tr_clock_6 .td_clock_22,
  #tr_clock_6 .td_clock_23,
  #tr_clock_7 .td_clock_10,
  #tr_clock_7 .td_clock_11,
  #tr_clock_7 .td_clock_12,
  #tr_clock_7 .td_clock_13,
  #tr_clock_7 .td_clock_14,
  #tr_clock_7 .td_clock_15,
  #tr_clock_7 .td_clock_16,
  #tr_clock_7 .td_clock_17,
  #tr_clock_7 .td_clock_18,
  #tr_clock_7 .td_clock_19,
  #tr_clock_7 .td_clock_20,
  #tr_clock_7 .td_clock_21,
  #tr_clock_7 .td_clock_22,
  #tr_clock_7 .td_clock_23,
  #tr_clock_8 .td_clock_8,
  #tr_clock_8 .td_clock_9,
  #tr_clock_8 .td_clock_23,
  #tr_clock_8 .td_clock_24,
  #tr_clock_9 .td_clock_8,
  #tr_clock_9 .td_clock_9,
  #tr_clock_9 .td_clock_23,
  #tr_clock_9 .td_clock_24,
  #tr_clock_10 .td_clock_7,
  #tr_clock_10 .td_clock_25,
  #tr_clock_10 .td_clock_26,
  #tr_clock_11 .td_clock_7,
  #tr_clock_11 .td_clock_25,
  #tr_clock_11 .td_clock_26,
  #tr_clock_12 .td_clock_7,
  #tr_clock_12 .td_clock_25,
  #tr_clock_12 .td_clock_26,
  #tr_clock_13 .td_clock_7,
  #tr_clock_13 .td_clock_25,
  #tr_clock_13 .td_clock_26,
  #tr_clock_14 .td_clock_7,
  #tr_clock_14 .td_clock_25,
  #tr_clock_14 .td_clock_26,
  #tr_clock_15 .td_clock_7,
  #tr_clock_15 .td_clock_25,
  #tr_clock_15 .td_clock_26,
  #tr_clock_16 .td_clock_7,
  #tr_clock_16 .td_clock_25,
  #tr_clock_16 .td_clock_26,
  #tr_clock_17 .td_clock_7,
  #tr_clock_17 .td_clock_25,
  #tr_clock_17 .td_clock_26,
  #tr_clock_18 .td_clock_7,
  #tr_clock_18 .td_clock_25,
  #tr_clock_18 .td_clock_26,
  #tr_clock_19 .td_clock_7,
  #tr_clock_19 .td_clock_25,
  #tr_clock_19 .td_clock_26,
  #tr_clock_20 .td_clock_7,
  #tr_clock_20 .td_clock_25,
  #tr_clock_20 .td_clock_26,
  #tr_clock_21 .td_clock_7,
  #tr_clock_21 .td_clock_25,
  #tr_clock_21 .td_clock_26,
  #tr_clock_22 .td_clock_7,
  #tr_clock_22 .td_clock_25,
  #tr_clock_22 .td_clock_26,
  #tr_clock_23 .td_clock_7,
  #tr_clock_23 .td_clock_25,
  #tr_clock_23 .td_clock_26,
  #tr_clock_24 .td_clock_8,
  #tr_clock_24 .td_clock_9,
  #tr_clock_24 .td_clock_24,
  #tr_clock_24 .td_clock_25,
  #tr_clock_25 .td_clock_10,
  #tr_clock_25 .td_clock_11,
  #tr_clock_25 .td_clock_12,
  #tr_clock_25 .td_clock_13,
  #tr_clock_25 .td_clock_14,
  #tr_clock_25 .td_clock_15,
  #tr_clock_25 .td_clock_16,
  #tr_clock_25 .td_clock_17,
  #tr_clock_25 .td_clock_18,
  #tr_clock_25 .td_clock_19,
  #tr_clock_25 .td_clock_20,
  #tr_clock_25 .td_clock_21,
  #tr_clock_25 .td_clock_22,
  #tr_clock_25 .td_clock_23,
  #tr_clock_26 .td_clock_10,
  #tr_clock_26 .td_clock_11,
  #tr_clock_26 .td_clock_12,
  #tr_clock_26 .td_clock_13,
  #tr_clock_26 .td_clock_14,
  #tr_clock_26 .td_clock_15,
  #tr_clock_26 .td_clock_16,
  #tr_clock_26 .td_clock_17,
  #tr_clock_26 .td_clock_18,
  #tr_clock_26 .td_clock_19,
  #tr_clock_26 .td_clock_20,
  #tr_clock_26 .td_clock_21,
  #tr_clock_26 .td_clock_22,
  #tr_clock_26 .td_clock_23`
)

// 水管
const pipe_color = document.querySelectorAll(
  `#tr_pipe_2 .td_pipe_1,
  #tr_pipe_2 .td_pipe_3,
  #tr_pipe_2 .td_pipe_8,
  #tr_pipe_2 .td_pipe_9,
  #tr_pipe_2 .td_pipe_10,
  #tr_pipe_2 .td_pipe_11,
  #tr_pipe_2 .td_pipe_12,
  #tr_pipe_2 .td_pipe_13,
  #tr_pipe_2 .td_pipe_14,
  #tr_pipe_3 .td_pipe_1,
  #tr_pipe_3 .td_pipe_3,
  #tr_pipe_3 .td_pipe_8,
  #tr_pipe_3 .td_pipe_9,
  #tr_pipe_3 .td_pipe_10,
  #tr_pipe_3 .td_pipe_11,
  #tr_pipe_3 .td_pipe_12,
  #tr_pipe_3 .td_pipe_13,
  #tr_pipe_3 .td_pipe_14,
  #tr_pipe_4 .td_pipe_1,
  #tr_pipe_4 .td_pipe_3,
  #tr_pipe_4 .td_pipe_8,
  #tr_pipe_4 .td_pipe_9,
  #tr_pipe_4 .td_pipe_10,
  #tr_pipe_4 .td_pipe_11,
  #tr_pipe_4 .td_pipe_12,
  #tr_pipe_4 .td_pipe_13,
  #tr_pipe_4 .td_pipe_14,
  #tr_pipe_5 .td_pipe_1,
  #tr_pipe_5 .td_pipe_3,
  #tr_pipe_5 .td_pipe_8,
  #tr_pipe_5 .td_pipe_9,
  #tr_pipe_5 .td_pipe_10,
  #tr_pipe_5 .td_pipe_11,
  #tr_pipe_5 .td_pipe_12,
  #tr_pipe_5 .td_pipe_13,
  #tr_pipe_5 .td_pipe_14,
  #tr_pipe_6 .td_pipe_1,
  #tr_pipe_6 .td_pipe_3,
  #tr_pipe_6 .td_pipe_8,
  #tr_pipe_6 .td_pipe_9,
  #tr_pipe_6 .td_pipe_10,
  #tr_pipe_6 .td_pipe_11,
  #tr_pipe_6 .td_pipe_12,
  #tr_pipe_6 .td_pipe_13,
  #tr_pipe_6 .td_pipe_14,
  #tr_pipe_8 .td_pipe_2,
  #tr_pipe_8 .td_pipe_3,
  #tr_pipe_8 .td_pipe_4,
  #tr_pipe_8 .td_pipe_5,
  #tr_pipe_8 .td_pipe_6,
  #tr_pipe_8 .td_pipe_7,
  #tr_pipe_8 .td_pipe_8,
  #tr_pipe_8 .td_pipe_9,
  #tr_pipe_8 .td_pipe_10,
  #tr_pipe_8 .td_pipe_11,
  #tr_pipe_8 .td_pipe_12,
  #tr_pipe_8 .td_pipe_13,
  #tr_pipe_9 .td_pipe_2,
  #tr_pipe_9 .td_pipe_3,
  #tr_pipe_9 .td_pipe_4,
  #tr_pipe_9 .td_pipe_5,
  #tr_pipe_9 .td_pipe_6,
  #tr_pipe_9 .td_pipe_7,
  #tr_pipe_9 .td_pipe_8,
  #tr_pipe_9 .td_pipe_9,
  #tr_pipe_9 .td_pipe_10,
  #tr_pipe_9 .td_pipe_11,
  #tr_pipe_9 .td_pipe_12,
  #tr_pipe_9 .td_pipe_13,
  #tr_pipe_1 .td_pipe_1,
#tr_pipe_1 .td_pipe_2,
#tr_pipe_1 .td_pipe_3,
#tr_pipe_1 .td_pipe_4,
#tr_pipe_1 .td_pipe_5,
#tr_pipe_1 .td_pipe_6,
#tr_pipe_1 .td_pipe_7,
#tr_pipe_1 .td_pipe_8,
#tr_pipe_1 .td_pipe_9,
#tr_pipe_1 .td_pipe_10,
#tr_pipe_1 .td_pipe_11,
#tr_pipe_1 .td_pipe_12,
#tr_pipe_1 .td_pipe_13,
#tr_pipe_1 .td_pipe_14,
#tr_pipe_2 .td_pipe_1,
#tr_pipe_2 .td_pipe_14,
#tr_pipe_3 .td_pipe_1,
#tr_pipe_3 .td_pipe_14,
#tr_pipe_4 .td_pipe_1,
#tr_pipe_4 .td_pipe_14,
#tr_pipe_5 .td_pipe_1,
#tr_pipe_5 .td_pipe_14,
#tr_pipe_6 .td_pipe_1,
#tr_pipe_6 .td_pipe_14,
#tr_pipe_7 .td_pipe_1,
#tr_pipe_7 .td_pipe_2,
#tr_pipe_7 .td_pipe_3,
#tr_pipe_7 .td_pipe_4,
#tr_pipe_7 .td_pipe_5,
#tr_pipe_7 .td_pipe_6,
#tr_pipe_7 .td_pipe_7,
#tr_pipe_7 .td_pipe_8,
#tr_pipe_7 .td_pipe_9,
#tr_pipe_7 .td_pipe_10,
#tr_pipe_7 .td_pipe_11,
#tr_pipe_7 .td_pipe_12,
#tr_pipe_7 .td_pipe_13,
#tr_pipe_7 .td_pipe_14,
#tr_pipe_8 .td_pipe_2,
#tr_pipe_8 .td_pipe_13,
#tr_pipe_9 .td_pipe_2,
#tr_pipe_9 .td_pipe_13,
#tr_pipe_2 .td_pipe_2,
#tr_pipe_2 .td_pipe_4,
#tr_pipe_2 .td_pipe_5,
#tr_pipe_2 .td_pipe_6,
#tr_pipe_2 .td_pipe_7,
#tr_pipe_2 .td_pipe_13,
#tr_pipe_3 .td_pipe_2,
#tr_pipe_3 .td_pipe_4,
#tr_pipe_3 .td_pipe_5,
#tr_pipe_3 .td_pipe_6,
#tr_pipe_3 .td_pipe_7,
#tr_pipe_3 .td_pipe_13,
#tr_pipe_4 .td_pipe_2,
#tr_pipe_4 .td_pipe_4,
#tr_pipe_4 .td_pipe_5,
#tr_pipe_4 .td_pipe_6,
#tr_pipe_4 .td_pipe_7,
#tr_pipe_4 .td_pipe_13,
#tr_pipe_5 .td_pipe_2,
#tr_pipe_5 .td_pipe_4,
#tr_pipe_5 .td_pipe_5,
#tr_pipe_5 .td_pipe_6,
#tr_pipe_5 .td_pipe_7,
#tr_pipe_5 .td_pipe_13,
#tr_pipe_6 .td_pipe_2,
#tr_pipe_6 .td_pipe_4,
#tr_pipe_6 .td_pipe_5,
#tr_pipe_6 .td_pipe_6,
#tr_pipe_6 .td_pipe_7,
#tr_pipe_6 .td_pipe_13,
#tr_pipe_8 .td_pipe_3,
#tr_pipe_8 .td_pipe_5,
#tr_pipe_8 .td_pipe_6,
#tr_pipe_8 .td_pipe_7,
#tr_pipe_8 .td_pipe_12,
#tr_pipe_9 .td_pipe_3,
#tr_pipe_9 .td_pipe_5,
#tr_pipe_9 .td_pipe_6,
#tr_pipe_9 .td_pipe_7,
#tr_pipe_9 .td_pipe_12
  `
)

// 馬力歐
const mario_color = document.querySelectorAll(
  `#tr_mario_1 .td_mario_4,
  #tr_mario_1 .td_mario_5,
  #tr_mario_1 .td_mario_6,
  #tr_mario_1 .td_mario_7,
  #tr_mario_1 .td_mario_8,
  #tr_mario_1 .td_mario_9,
  #tr_mario_2 .td_mario_3,
  #tr_mario_2 .td_mario_4,
  #tr_mario_2 .td_mario_5,
  #tr_mario_2 .td_mario_6,
  #tr_mario_2 .td_mario_7,
  #tr_mario_2 .td_mario_8,
  #tr_mario_2 .td_mario_9,
  #tr_mario_2 .td_mario_10,
  #tr_mario_2 .td_mario_11,
  #tr_mario_2 .td_mario_12,
  #tr_mario_2 .td_mario_13,
  #tr_mario_8 .td_mario_6,
  #tr_mario_9 .td_mario_6,
  #tr_mario_9 .td_mario_9,
  #tr_mario_10 .td_mario_6,
  #tr_mario_10 .td_mario_7,
  #tr_mario_10 .td_mario_8,
  #tr_mario_10 .td_mario_9,
  #tr_mario_11 .td_mario_5,
  #tr_mario_11 .td_mario_7,
  #tr_mario_11 .td_mario_8,
  #tr_mario_11 .td_mario_10,
  #tr_mario_12 .td_mario_5,
  #tr_mario_12 .td_mario_6,
  #tr_mario_12 .td_mario_7,
  #tr_mario_12 .td_mario_8,
  #tr_mario_12 .td_mario_9,
  #tr_mario_12 .td_mario_10,
  #tr_mario_13 .td_mario_3,
  #tr_mario_13 .td_mario_4,
  #tr_mario_13 .td_mario_5,
  #tr_mario_13 .td_mario_6,
  #tr_mario_13 .td_mario_7,
  #tr_mario_13 .td_mario_8,
  #tr_mario_13 .td_mario_9,
  #tr_mario_13 .td_mario_10,
  #tr_mario_13 .td_mario_11,
  #tr_mario_13 .td_mario_12,
  #tr_mario_14 .td_mario_3,
  #tr_mario_14 .td_mario_4,
  #tr_mario_14 .td_mario_5,
  #tr_mario_14 .td_mario_6,
  #tr_mario_14 .td_mario_9,
  #tr_mario_14 .td_mario_10,
  #tr_mario_14 .td_mario_11,
  #tr_mario_14 .td_mario_12,
  #tr_mario_3 .td_mario_3,
#tr_mario_3 .td_mario_4,
#tr_mario_3 .td_mario_5,
#tr_mario_3 .td_mario_6,
#tr_mario_3 .td_mario_9,
#tr_mario_4 .td_mario_2,
#tr_mario_4 .td_mario_4,
#tr_mario_4 .td_mario_5,
#tr_mario_4 .td_mario_9,
#tr_mario_5 .td_mario_2,
#tr_mario_5 .td_mario_4,
#tr_mario_5 .td_mario_5,
#tr_mario_5 .td_mario_6,
#tr_mario_5 .td_mario_10,
#tr_mario_6 .td_mario_2,
#tr_mario_6 .td_mario_3,
#tr_mario_6 .td_mario_4,
#tr_mario_6 .td_mario_9,
#tr_mario_6 .td_mario_10,
#tr_mario_6 .td_mario_11,
#tr_mario_6 .td_mario_12,
#tr_mario_6 .td_mario_13,
#tr_mario_8 .td_mario_3,
#tr_mario_8 .td_mario_4,
#tr_mario_8 .td_mario_5,
#tr_mario_8 .td_mario_7,
#tr_mario_8 .td_mario_8,
#tr_mario_8 .td_mario_9,
#tr_mario_9 .td_mario_2,
#tr_mario_9 .td_mario_3,
#tr_mario_9 .td_mario_4,
#tr_mario_9 .td_mario_5,
#tr_mario_9 .td_mario_7,
#tr_mario_9 .td_mario_8,
#tr_mario_9 .td_mario_10,
#tr_mario_9 .td_mario_11,
#tr_mario_9 .td_mario_12,
#tr_mario_9 .td_mario_13,
#tr_mario_10 .td_mario_1,
#tr_mario_10 .td_mario_2,
#tr_mario_10 .td_mario_3,
#tr_mario_10 .td_mario_4,
#tr_mario_10 .td_mario_5,
#tr_mario_10 .td_mario_10,
#tr_mario_10 .td_mario_11,
#tr_mario_10 .td_mario_12,
#tr_mario_10 .td_mario_13,
#tr_mario_10 .td_mario_14,
#tr_mario_11 .td_mario_3,
#tr_mario_11 .td_mario_4,
#tr_mario_11 .td_mario_11,
#tr_mario_11 .td_mario_12,
#tr_mario_15 .td_mario_2,
#tr_mario_15 .td_mario_3,
#tr_mario_15 .td_mario_4,
#tr_mario_15 .td_mario_5,
#tr_mario_15 .td_mario_10,
#tr_mario_15 .td_mario_11,
#tr_mario_15 .td_mario_12,
#tr_mario_15 .td_mario_13,
#tr_mario_16 .td_mario_1,
#tr_mario_16 .td_mario_2,
#tr_mario_16 .td_mario_3,
#tr_mario_16 .td_mario_4,
#tr_mario_16 .td_mario_5,
#tr_mario_16 .td_mario_10,
#tr_mario_16 .td_mario_11,
#tr_mario_16 .td_mario_12,
#tr_mario_16 .td_mario_13,
#tr_mario_16 .td_mario_14,
#tr_mario_3 .td_mario_7,
#tr_mario_3 .td_mario_8,
#tr_mario_3 .td_mario_10,
#tr_mario_4 .td_mario_3,
#tr_mario_4 .td_mario_6,
#tr_mario_4 .td_mario_7,
#tr_mario_4 .td_mario_8,
#tr_mario_4 .td_mario_10,
#tr_mario_4 .td_mario_11,
#tr_mario_4 .td_mario_12,
#tr_mario_4 .td_mario_13,
#tr_mario_5 .td_mario_3,
#tr_mario_5 .td_mario_7,
#tr_mario_5 .td_mario_8,
#tr_mario_5 .td_mario_9,
#tr_mario_5 .td_mario_11,
#tr_mario_5 .td_mario_12,
#tr_mario_5 .td_mario_13,
#tr_mario_5 .td_mario_14,
#tr_mario_6 .td_mario_5,
#tr_mario_6 .td_mario_6,
#tr_mario_6 .td_mario_7,
#tr_mario_6 .td_mario_8,
#tr_mario_7 .td_mario_4,
#tr_mario_7 .td_mario_5,
#tr_mario_7 .td_mario_6,
#tr_mario_7 .td_mario_7,
#tr_mario_7 .td_mario_8,
#tr_mario_7 .td_mario_9,
#tr_mario_7 .td_mario_10,
#tr_mario_7 .td_mario_11,
#tr_mario_7 .td_mario_12,
#tr_mario_11 .td_mario_1,
#tr_mario_11 .td_mario_2,
#tr_mario_11 .td_mario_6,
#tr_mario_11 .td_mario_9,
#tr_mario_11 .td_mario_13,
#tr_mario_11 .td_mario_14,
#tr_mario_12 .td_mario_1,
#tr_mario_12 .td_mario_2,
#tr_mario_12 .td_mario_3,
#tr_mario_12 .td_mario_4,
#tr_mario_12 .td_mario_11,
#tr_mario_12 .td_mario_12,
#tr_mario_12 .td_mario_13,
#tr_mario_12 .td_mario_14,
#tr_mario_13 .td_mario_1,
#tr_mario_13 .td_mario_2,
#tr_mario_13 .td_mario_13,
#tr_mario_13 .td_mario_14
  `
)

// 壞香菇(還未用)

if (bad_mushroom_R.style.display === 'block') {
  const bad_mushroom_R_color = document.querySelectorAll(`
  #tr_bad_mushroom_R_1 .td_bad_mushroom_6,
  #tr_bad_mushroom_R_1 .td_bad_mushroom_7,
  #tr_bad_mushroom_R_2 .td_bad_mushroom_5,
  #tr_bad_mushroom_R_2 .td_bad_mushroom_6,
  #tr_bad_mushroom_R_2 .td_bad_mushroom_7,
  #tr_bad_mushroom_R_2 .td_bad_mushroom_8,
  #tr_bad_mushroom_R_3 .td_bad_mushroom_4,
  #tr_bad_mushroom_R_3 .td_bad_mushroom_5,
  #tr_bad_mushroom_R_3 .td_bad_mushroom_6,
  #tr_bad_mushroom_R_3 .td_bad_mushroom_7,
  #tr_bad_mushroom_R_3 .td_bad_mushroom_8,
  #tr_bad_mushroom_R_3 .td_bad_mushroom_9,
  #tr_bad_mushroom_R_4 .td_bad_mushroom_5,
  #tr_bad_mushroom_R_4 .td_bad_mushroom_6,
  #tr_bad_mushroom_R_4 .td_bad_mushroom_7,
  #tr_bad_mushroom_R_4 .td_bad_mushroom_8,
  #tr_bad_mushroom_R_5 .td_bad_mushroom_2,
  #tr_bad_mushroom_R_5 .td_bad_mushroom_3,
  #tr_bad_mushroom_R_5 .td_bad_mushroom_6,
  #tr_bad_mushroom_R_5 .td_bad_mushroom_7,
  #tr_bad_mushroom_R_5 .td_bad_mushroom_9,
  #tr_bad_mushroom_R_5 .td_bad_mushroom_10,
  #tr_bad_mushroom_R_5 .td_bad_mushroom_11,
  #tr_bad_mushroom_R_6 .td_bad_mushroom_2,
  #tr_bad_mushroom_R_6 .td_bad_mushroom_3,
  #tr_bad_mushroom_R_6 .td_bad_mushroom_4,
  #tr_bad_mushroom_R_6 .td_bad_mushroom_9,
  #tr_bad_mushroom_R_6 .td_bad_mushroom_10,
  #tr_bad_mushroom_R_6 .td_bad_mushroom_11,
  #tr_bad_mushroom_R_7 .td_bad_mushroom_1,
  #tr_bad_mushroom_R_7 .td_bad_mushroom_2,
  #tr_bad_mushroom_R_7 .td_bad_mushroom_3,
  #tr_bad_mushroom_R_7 .td_bad_mushroom_4,
  #tr_bad_mushroom_R_7 .td_bad_mushroom_5,
  #tr_bad_mushroom_R_7 .td_bad_mushroom_6,
  #tr_bad_mushroom_R_7 .td_bad_mushroom_7,
  #tr_bad_mushroom_R_7 .td_bad_mushroom_8,
  #tr_bad_mushroom_R_7 .td_bad_mushroom_9,
  #tr_bad_mushroom_R_7 .td_bad_mushroom_10,
  #tr_bad_mushroom_R_7 .td_bad_mushroom_11,
  #tr_bad_mushroom_R_7 .td_bad_mushroom_12,
  #tr_bad_mushroom_R_8 .td_bad_mushroom_1,
  #tr_bad_mushroom_R_8 .td_bad_mushroom_2,
  #tr_bad_mushroom_R_8 .td_bad_mushroom_3,
  #tr_bad_mushroom_R_8 .td_bad_mushroom_4,
  #tr_bad_mushroom_R_8 .td_bad_mushroom_5,
  #tr_bad_mushroom_R_8 .td_bad_mushroom_6,
  #tr_bad_mushroom_R_8 .td_bad_mushroom_7,
  #tr_bad_mushroom_R_8 .td_bad_mushroom_8,
  #tr_bad_mushroom_R_8 .td_bad_mushroom_9,
  #tr_bad_mushroom_R_8 .td_bad_mushroom_10,
  #tr_bad_mushroom_R_8 .td_bad_mushroom_11,
  #tr_bad_mushroom_R_8 .td_bad_mushroom_12,
  #tr_bad_mushroom_R_9 .td_bad_mushroom_2,
  #tr_bad_mushroom_R_9 .td_bad_mushroom_3,
  #tr_bad_mushroom_R_9 .td_bad_mushroom_10,
  #tr_bad_mushroom_R_9 .td_bad_mushroom_11,
  #tr_bad_mushroom_R_9 .td_bad_mushroom_4,
  #tr_bad_mushroom_R_9 .td_bad_mushroom_5,
  #tr_bad_mushroom_R_9 .td_bad_mushroom_6,
  #tr_bad_mushroom_R_9 .td_bad_mushroom_7,
  #tr_bad_mushroom_R_9 .td_bad_mushroom_8,
  #tr_bad_mushroom_R_9 .td_bad_mushroom_9,
  #tr_bad_mushroom_R_10 .td_bad_mushroom_4,
  #tr_bad_mushroom_R_10 .td_bad_mushroom_5,
  #tr_bad_mushroom_R_10 .td_bad_mushroom_6,
  #tr_bad_mushroom_R_10 .td_bad_mushroom_7,
  #tr_bad_mushroom_R_10 .td_bad_mushroom_8,
  #tr_bad_mushroom_R_10 .td_bad_mushroom_9,
  #tr_bad_mushroom_R_11 .td_bad_mushroom_5,
  #tr_bad_mushroom_R_11 .td_bad_mushroom_6,
  #tr_bad_mushroom_R_11 .td_bad_mushroom_7,
  #tr_bad_mushroom_R_11 .td_bad_mushroom_8,
  #tr_bad_mushroom_R_12 .td_bad_mushroom_6,
  #tr_bad_mushroom_R_12 .td_bad_mushroom_7,
  #tr_bad_mushroom_R_4 .td_bad_mushroom_3,
  #tr_bad_mushroom_R_4 .td_bad_mushroom_4,
  #tr_bad_mushroom_R_4 .td_bad_mushroom_9,
  #tr_bad_mushroom_R_4 .td_bad_mushroom_10,
  #tr_bad_mushroom_R_5 .td_bad_mushroom_5,
  #tr_bad_mushroom_R_5 .td_bad_mushroom_8,
  #tr_bad_mushroom_R_6 .td_bad_mushroom_5,
  #tr_bad_mushroom_R_6 .td_bad_mushroom_6,
  #tr_bad_mushroom_R_6 .td_bad_mushroom_7,
  #tr_bad_mushroom_R_6 .td_bad_mushroom_8,
  #tr_bad_mushroom_R_10 .td_bad_mushroom_10,
  #tr_bad_mushroom_R_11 .td_bad_mushroom_3,
  #tr_bad_mushroom_R_11 .td_bad_mushroom_4,
  #tr_bad_mushroom_R_11 .td_bad_mushroom_8,
  #tr_bad_mushroom_R_11 .td_bad_mushroom_9,
  #tr_bad_mushroom_R_11 .td_bad_mushroom_10,
  #tr_bad_mushroom_R_11 .td_bad_mushroom_11,
  #tr_bad_mushroom_R_12 .td_bad_mushroom_4,
  #tr_bad_mushroom_R_12 .td_bad_mushroom_5,
  #tr_bad_mushroom_R_12 .td_bad_mushroom_8,
  #tr_bad_mushroom_R_12 .td_bad_mushroom_9,
  #tr_bad_mushroom_R_12 .td_bad_mushroom_10,
  #tr_bad_mushroom_R_12 .td_bad_mushroom_11,
  #tr_bad_mushroom_R_7 .td_bad_mushroom_5,
  #tr_bad_mushroom_R_7 .td_bad_mushroom_8,
  `)
}
if (bad_mushroom_L.style.display === 'block') {
  const bad_mushroom_R_color = document.querySelectorAll(
    `#tr_bad_mushroom_L_1 .td_bad_mushroom_6,
    #tr_bad_mushroom_L_1 .td_bad_mushroom_7,
    #tr_bad_mushroom_L_2 .td_bad_mushroom_5,
    #tr_bad_mushroom_L_2 .td_bad_mushroom_6,
    #tr_bad_mushroom_L_2 .td_bad_mushroom_7,
    #tr_bad_mushroom_L_2 .td_bad_mushroom_8,
    #tr_bad_mushroom_L_3 .td_bad_mushroom_4,
    #tr_bad_mushroom_L_3 .td_bad_mushroom_5,
    #tr_bad_mushroom_L_3 .td_bad_mushroom_6,
    #tr_bad_mushroom_L_3 .td_bad_mushroom_7,
    #tr_bad_mushroom_L_3 .td_bad_mushroom_8,
    #tr_bad_mushroom_L_3 .td_bad_mushroom_9,
    #tr_bad_mushroom_L_4 .td_bad_mushroom_5,
    #tr_bad_mushroom_L_4 .td_bad_mushroom_6,
    #tr_bad_mushroom_L_4 .td_bad_mushroom_7,
    #tr_bad_mushroom_L_4 .td_bad_mushroom_8,
    #tr_bad_mushroom_L_5 .td_bad_mushroom_2,
    #tr_bad_mushroom_L_5 .td_bad_mushroom_3,
    #tr_bad_mushroom_L_5 .td_bad_mushroom_6,
    #tr_bad_mushroom_L_5 .td_bad_mushroom_7,
    #tr_bad_mushroom_L_5 .td_bad_mushroom_9,
    #tr_bad_mushroom_L_5 .td_bad_mushroom_10,
    #tr_bad_mushroom_L_5 .td_bad_mushroom_11,
    #tr_bad_mushroom_L_6 .td_bad_mushroom_2,
    #tr_bad_mushroom_L_6 .td_bad_mushroom_3,
    #tr_bad_mushroom_L_6 .td_bad_mushroom_4,
    #tr_bad_mushroom_L_6 .td_bad_mushroom_9,
    #tr_bad_mushroom_L_6 .td_bad_mushroom_10,
    #tr_bad_mushroom_L_6 .td_bad_mushroom_11,
    #tr_bad_mushroom_L_7 .td_bad_mushroom_1,
    #tr_bad_mushroom_L_7 .td_bad_mushroom_2,
    #tr_bad_mushroom_L_7 .td_bad_mushroom_3,
    #tr_bad_mushroom_L_7 .td_bad_mushroom_4,
    #tr_bad_mushroom_L_7 .td_bad_mushroom_5,
    #tr_bad_mushroom_L_7 .td_bad_mushroom_6,
    #tr_bad_mushroom_L_7 .td_bad_mushroom_7,
    #tr_bad_mushroom_L_7 .td_bad_mushroom_8,
    #tr_bad_mushroom_L_7 .td_bad_mushroom_9,
    #tr_bad_mushroom_L_7 .td_bad_mushroom_10,
    #tr_bad_mushroom_L_7 .td_bad_mushroom_11,
    #tr_bad_mushroom_L_7 .td_bad_mushroom_12,
    #tr_bad_mushroom_L_8 .td_bad_mushroom_1,
    #tr_bad_mushroom_L_8 .td_bad_mushroom_2,
    #tr_bad_mushroom_L_8 .td_bad_mushroom_3,
    #tr_bad_mushroom_L_8 .td_bad_mushroom_4,
    #tr_bad_mushroom_L_8 .td_bad_mushroom_5,
    #tr_bad_mushroom_L_8 .td_bad_mushroom_6,
    #tr_bad_mushroom_L_8 .td_bad_mushroom_7,
    #tr_bad_mushroom_L_8 .td_bad_mushroom_8,
    #tr_bad_mushroom_L_8 .td_bad_mushroom_9,
    #tr_bad_mushroom_L_8 .td_bad_mushroom_10,
    #tr_bad_mushroom_L_8 .td_bad_mushroom_11,
    #tr_bad_mushroom_L_8 .td_bad_mushroom_12,
    #tr_bad_mushroom_L_9 .td_bad_mushroom_2,
    #tr_bad_mushroom_L_9 .td_bad_mushroom_3,
    #tr_bad_mushroom_L_9 .td_bad_mushroom_10,
    #tr_bad_mushroom_L_9 .td_bad_mushroom_11,
    #tr_bad_mushroom_L_9 .td_bad_mushroom_4,
#tr_bad_mushroom_L_9 .td_bad_mushroom_5,
#tr_bad_mushroom_L_9 .td_bad_mushroom_6,
#tr_bad_mushroom_L_9 .td_bad_mushroom_7,
#tr_bad_mushroom_L_9 .td_bad_mushroom_8,
#tr_bad_mushroom_L_9 .td_bad_mushroom_9,
#tr_bad_mushroom_L_10 .td_bad_mushroom_4,
#tr_bad_mushroom_L_10 .td_bad_mushroom_5,
#tr_bad_mushroom_L_10 .td_bad_mushroom_6,
#tr_bad_mushroom_L_10 .td_bad_mushroom_7,
#tr_bad_mushroom_L_10 .td_bad_mushroom_8,
#tr_bad_mushroom_L_10 .td_bad_mushroom_9,
#tr_bad_mushroom_L_11 .td_bad_mushroom_6,
#tr_bad_mushroom_L_11 .td_bad_mushroom_7,
#tr_bad_mushroom_L_11 .td_bad_mushroom_8,
#tr_bad_mushroom_L_12 .td_bad_mushroom_6,
#tr_bad_mushroom_L_12 .td_bad_mushroom_7,
#tr_bad_mushroom_L_4 .td_bad_mushroom_3,
#tr_bad_mushroom_L_4 .td_bad_mushroom_4,
#tr_bad_mushroom_L_4 .td_bad_mushroom_9,
#tr_bad_mushroom_L_4 .td_bad_mushroom_10,
#tr_bad_mushroom_L_5 .td_bad_mushroom_5,
#tr_bad_mushroom_L_5 .td_bad_mushroom_8,
#tr_bad_mushroom_L_6 .td_bad_mushroom_5,
#tr_bad_mushroom_L_6 .td_bad_mushroom_6,
#tr_bad_mushroom_L_6 .td_bad_mushroom_7,
#tr_bad_mushroom_L_6 .td_bad_mushroom_8,
#tr_bad_mushroom_L_10 .td_bad_mushroom_3,
#tr_bad_mushroom_L_11 .td_bad_mushroom_2,
#tr_bad_mushroom_L_11 .td_bad_mushroom_3,
#tr_bad_mushroom_L_11 .td_bad_mushroom_4,
#tr_bad_mushroom_L_11 .td_bad_mushroom_5,
#tr_bad_mushroom_L_11 .td_bad_mushroom_9,
#tr_bad_mushroom_L_11 .td_bad_mushroom_10,
#tr_bad_mushroom_L_12 .td_bad_mushroom_2,
#tr_bad_mushroom_L_12 .td_bad_mushroom_3,
#tr_bad_mushroom_L_12 .td_bad_mushroom_4,
#tr_bad_mushroom_L_12 .td_bad_mushroom_5,
#tr_bad_mushroom_L_12 .td_bad_mushroom_8,
#tr_bad_mushroom_L_12 .td_bad_mushroom_9,
#tr_bad_mushroom_L_5 .td_bad_mushroom_4,
#tr_bad_mushroom_L_5 .td_bad_mushroom_9,
#tr_bad_mushroom_L_6 .td_bad_mushroom_4,
#tr_bad_mushroom_L_6 .td_bad_mushroom_9,
#tr_bad_mushroom_L_7 .td_bad_mushroom_4,
#tr_bad_mushroom_L_7 .td_bad_mushroom_5,
#tr_bad_mushroom_L_7 .td_bad_mushroom_8,
#tr_bad_mushroom_L_7 .td_bad_mushroom_9
    `
  )
}

// 數字
const number_color = document.querySelectorAll(
  `.tr_colon_2 .td_colon_1,
  .tr_colon_4 .td_colon_1,
  .tr_zero_1 .td_zero_2,
  .tr_zero_1 .td_zero_3,
  .tr_zero_2 .td_zero_1,
  .tr_zero_2 .td_zero_4,
  .tr_zero_3 .td_zero_1,
  .tr_zero_3 .td_zero_4,
  .tr_zero_4 .td_zero_1,
  .tr_zero_4 .td_zero_4,
  .tr_zero_5 .td_zero_2,
  .tr_zero_5 .td_zero_3,
  .tr_one_1 .td_one_2,
.tr_one_1 .td_one_3,
.tr_one_2 .td_one_1,
.tr_one_2 .td_one_3,
.tr_one_3 .td_one_3,
.tr_one_4 .td_one_3,
.tr_one_5 .td_one_1,
.tr_one_5 .td_one_2,
.tr_one_5 .td_one_3,
.tr_one_5 .td_one_4,
.tr_two_1 .td_two_1,
.tr_two_1 .td_two_2,
.tr_two_1 .td_two_3,
.tr_two_1 .td_two_4,
.tr_two_2 .td_two_4,
.tr_two_3 .td_two_3,
.tr_two_4 .td_two_2,
.tr_two_5 .td_two_1,
.tr_two_5 .td_two_2,
.tr_two_5 .td_two_3,
.tr_two_5 .td_two_4,
.tr_three_1 .td_three_1,
.tr_three_1 .td_three_2,
.tr_three_1 .td_three_3,
.tr_three_1 .td_three_4,
.tr_three_2 .td_three_4,
.tr_three_3 .td_three_1,
.tr_three_3 .td_three_2,
.tr_three_3 .td_three_3,
.tr_three_3 .td_three_4,
.tr_three_4 .td_three_4,
.tr_three_5 .td_three_1,
.tr_three_5 .td_three_2,
.tr_three_5 .td_three_3,
.tr_three_5 .td_three_4,
.tr_four_1 .td_four_2,
.tr_four_1 .td_four_3,
.tr_four_2 .td_four_1,
.tr_four_2 .td_four_3,
.tr_four_3 .td_four_1,
.tr_four_3 .td_four_3,
.tr_four_4 .td_four_1,
.tr_four_4 .td_four_2,
.tr_four_4 .td_four_3,
.tr_four_4 .td_four_4,
.tr_four_5 .td_four_3,
.tr_five_1 .td_five_1,
.tr_five_1 .td_five_2,
.tr_five_1 .td_five_3,
.tr_five_1 .td_five_4,
.tr_five_2 .td_five_1,
.tr_five_3 .td_five_1,
.tr_five_3 .td_five_2,
.tr_five_3 .td_five_3,
.tr_five_3 .td_five_4,
.tr_five_4 .td_five_4,
.tr_five_5 .td_five_1,
.tr_five_5 .td_five_2,
.tr_five_5 .td_five_3,
.tr_five_5 .td_five_4,
.tr_six_1 .td_six_1,
.tr_six_1 .td_six_2,
.tr_six_1 .td_six_3,
.tr_six_1 .td_six_4,
.tr_six_2 .td_six_1,
.tr_six_3 .td_six_1,
.tr_six_3 .td_six_2,
.tr_six_3 .td_six_3,
.tr_six_3 .td_six_4,
.tr_six_4 .td_six_1,
.tr_six_4 .td_six_4,
.tr_six_5 .td_six_1,
.tr_six_5 .td_six_2,
.tr_six_5 .td_six_3,
.tr_six_5 .td_six_4,
.tr_seven_1 .td_seven_1,
.tr_seven_1 .td_seven_2,
.tr_seven_1 .td_seven_3,
.tr_seven_1 .td_seven_4,
.tr_seven_2 .td_seven_4,
.tr_seven_3 .td_seven_3,
.tr_seven_4 .td_seven_2,
.tr_seven_5 .td_seven_2,
.tr_eight_1 .td_eight_1,
.tr_eight_1 .td_eight_2,
.tr_eight_1 .td_eight_3,
.tr_eight_1 .td_eight_4,
.tr_eight_2 .td_eight_1,
.tr_eight_2 .td_eight_4,
.tr_eight_3 .td_eight_1,
.tr_eight_3 .td_eight_2,
.tr_eight_3 .td_eight_3,
.tr_eight_3 .td_eight_4,
.tr_eight_4 .td_eight_1,
.tr_eight_4 .td_eight_4,
.tr_eight_5 .td_eight_1,
.tr_eight_5 .td_eight_2,
.tr_eight_5 .td_eight_3,
.tr_eight_5 .td_eight_4,
.tr_nine_1 .td_nine_1,
.tr_nine_1 .td_nine_2,
.tr_nine_1 .td_nine_3,
.tr_nine_1 .td_nine_4,
.tr_nine_2 .td_nine_1,
.tr_nine_2 .td_nine_4,
.tr_nine_3 .td_nine_1,
.tr_nine_3 .td_nine_2,
.tr_nine_3 .td_nine_3,
.tr_nine_3 .td_nine_4,
.tr_nine_4 .td_nine_4,
.tr_nine_5 .td_nine_1,
.tr_nine_5 .td_nine_2,
.tr_nine_5 .td_nine_3,
.tr_nine_5 .td_nine_4

`
)

// 天上石頭
const upStone_color = document.querySelectorAll(`
.td_upStone
`)

// 天上石頭-L
const upStone_color_L = document.querySelectorAll(`
#tr_upStone_1 .td_upStone_1,
#tr_upStone_2 .td_upStone_1,
#tr_upStone_3 .td_upStone_1,
#tr_upStone_3 .td_upStone_3,
#tr_upStone_4 .td_upStone_1,
#tr_upStone_5 .td_upStone_1,
#tr_upStone_6 .td_upStone_1,
#tr_upStone_6 .td_upStone_3,
#tr_upStone_7 .td_upStone_1,
#tr_upStone_7 .td_upStone_3`)
// 天上石頭-R
// 天上石頭-B
// 天上石頭-T

// 地上石頭
const downStone_color = document.querySelectorAll(`
.td_stone
`)

// 按鈕
const btnOutside = document.querySelectorAll(
  `  .tr_btn_1 .td_btn_1,
  .tr_btn_1 .td_btn_2,
  .tr_btn_1 .td_btn_3,
  .tr_btn_2 .td_btn_1,
  .tr_btn_2 .td_btn_2,
  .tr_btn_2 .td_btn_3,
  .tr_btn_3 .td_btn_1,
  .tr_btn_3 .td_btn_2,
  .tr_btn_3 .td_btn_3
  `
)

const btn1_1 = document.querySelectorAll(`.tr_btn_1 .td_btn_1 `)
const btn1_2 = document.querySelectorAll(`.tr_btn_1 .td_btn_2 `)
const btn1_3 = document.querySelectorAll(`.tr_btn_1 .td_btn_3 `)
const btn2_1 = document.querySelectorAll(`.tr_btn_2 .td_btn_1 `)
const btn2_2 = document.querySelectorAll(`.tr_btn_2 .td_btn_2 `)
const btn2_3 = document.querySelectorAll(`.tr_btn_2 .td_btn_3 `)
const btn3_1 = document.querySelectorAll(`.tr_btn_3 .td_btn_1 `)
const btn3_2 = document.querySelectorAll(`.tr_btn_3 .td_btn_2 `)
const btn3_3 = document.querySelectorAll(`.tr_btn_3 .td_btn_3 `)

const td_board = document.querySelectorAll('.td_board')
const td_line = document.querySelectorAll('.td_line')

const board_right = document.querySelectorAll(`
#tr_board_1 .td_board_22,
#tr_board_2 .td_board_22,
#tr_board_3 .td_board_22,
#tr_board_4 .td_board_22,
#tr_board_5 .td_board_22,
#tr_board_6 .td_board_22`)

const board_bottom = document.querySelectorAll(`
#tr_board_6 .td_board_1,
#tr_board_6 .td_board_2,
#tr_board_6 .td_board_3,
#tr_board_6 .td_board_4,
#tr_board_6 .td_board_5,
#tr_board_6 .td_board_6,
#tr_board_6 .td_board_7,
#tr_board_6 .td_board_8,
#tr_board_6 .td_board_9,
#tr_board_6 .td_board_10,
#tr_board_6 .td_board_11,
#tr_board_6 .td_board_12,
#tr_board_6 .td_board_13,
#tr_board_6 .td_board_14,
#tr_board_6 .td_board_15,
#tr_board_6 .td_board_16,
#tr_board_6 .td_board_17,
#tr_board_6 .td_board_18,
#tr_board_6 .td_board_19,
#tr_board_6 .td_board_20,
#tr_board_6 .td_board_21,
#tr_board_6 .td_board_22`)

const date = new Date()
const hour = date.getHours()
const min = date.getMinutes()
const tens_min = Math.floor(min / 10)
const sec = date.getSeconds()
const ones_sec = sec % 10

const background_change_night = () => {
  for (const el of background_color) {
    el.style.background = '#000'
    el.style.border = '0.05px solid rgb(46, 46, 46)'
  }
  for (const el2 of clock_black) {
    el2.style.border = '0.05px solid rgb(100, 100, 100)'
    el2.style.background = '#000'
  }
  for (const el3 of clock_red) {
    el3.style.border = '0.05px solid rgb(100, 100, 100)'
  }
  for (const el4 of clock_yellow) {
    el4.style.border = '0.05px solid rgb(100, 100, 100)'
  }
  for (const el5 of clock_green) {
    el5.style.border = '0.05px solid rgb(150, 150, 150)'
    el5.style.background = 'rgb(25, 240, 255)'
  }
  for (const el6 of pipe_color) {
    el6.style.border = '0.05px solid rgb(150, 150, 150)'
  }
  for (const el7 of mario_color) {
    el7.style.border = '0.05px solid rgb(150, 150, 150)'
  }
  for (const el8 of number_color) {
    el8.style.border = '0.05px solid rgb(46, 46, 46)'
    el8.style.background = '#fff'
    el8.style.boxShadow = '0px 0px 10px rgb(25, 240, 255)'
  }
  for (const el9 of btnOutside) {
    el9.style.boxShadow = '0px 0px 10px rgb(25, 240, 255)'
  }

  for (const el10 of td_board) {
    el10.style.border = '0.05px solid  rgb(46, 46, 46)'
    el10.style.boxShadow = '0px 0px 10px rgb(148, 96, 54)'
  }

  for (const el11 of board_right) {
    el11.style.borderRight = '5px solid rgb(153, 110, 67)'
  }

  for (const el12 of board_bottom) {
    el12.style.borderBottom = '5px solid rgb(153, 110, 67)'
  }

  for (const el13 of td_line) {
    el13.style.boxShadow = '0px 0px 10px rgb(148, 96, 54)'
    el13.style.border = '0.05px solid  rgb(46, 46, 46)'
    el13.style.borderRight = '5px solid rgb(153, 110, 67)'
  }

  body.style.background = 'rgb(0,0,0)'
}

const background_change_sun = () => {
  for (const el of background_color) {
    el.style.background = 'rgb(255, 238, 208)'
    el.style.border = '0.05px solid rgb(218, 218, 218)'
  }
  for (const el2 of clock_black) {
    el2.style.border = '0.05px solid  rgb(218, 218, 218)'
  }
  for (const el3 of clock_red) {
    el3.style.border = '0.05px solid  rgb(218, 218, 218)'
  }
  for (const el4 of clock_yellow) {
    el4.style.border = '0.05px solid  rgb(218, 218, 218)'
  }
  for (const el5 of clock_green) {
    el5.style.border = '0.05px solid  rgb(218, 218, 218)'
    el5.style.background = 'rgb(70, 156, 255)'
  }
  for (const el6 of pipe_color) {
    el6.style.border = '0.05px solid rgb(218, 218, 218)'
  }
  for (const el7 of mario_color) {
    el7.style.border = '0.05px solid rgb(218, 218, 218)'
  }
  for (const el8 of number_color) {
    el8.style.border = '0.05px solid rgb(218, 218, 218)'
    el8.style.background = '#000'
    el8.style.boxShadow = '0px 0px 0px rgb(148, 96, 54)'
  }

  for (const el10 of td_board) {
    el10.style.border = '0.05px solid  rgb(46, 46, 46)'
    el10.style.boxShadow = ' '
  }

  for (const el11 of board_right) {
    el11.style.borderRight = '5px solid rgb(153, 110, 67)'
  }

  for (const el12 of board_bottom) {
    el12.style.borderBottom = '5px solid rgb(153, 110, 67)'
  }

  for (const el13 of td_line) {
    el13.style.boxShadow = '0px 0px 0px rgb(148, 96, 54) '
    el13.style.border = '0.05px solid  rgb(46, 46, 46)'
    el13.style.borderRight = '5px solid rgb(153, 110, 67)'
  }

  for (const bt1 of btn1_1) {
    bt1.style.boxShadow = ' -2.5px -2.5px 0px #000'
  }
  for (const bt2 of btn1_2) {
    bt2.style.boxShadow = '0 -2.5px 0px #000'
  }
  for (const bt3 of btn1_3) {
    bt3.style.boxShadow = '2.5px -2.5px 0px #000'
  }
  for (const bt4 of btn2_1) {
    bt4.style.boxShadow = '-2.5px 0 0px #000'
  }
  for (const bt5 of btn2_2) {
    bt5.style.boxShadow = ''
  }
  for (const bt6 of btn2_3) {
    bt6.style.boxShadow = '2.5px 0 0px #000'
  }
  for (const bt7 of btn3_1) {
    bt7.style.boxShadow = '-2.5px 2.5px 0px #000'
  }
  for (const bt8 of btn3_2) {
    bt8.style.boxShadow = '0 2.5px 0px #000'
  }
  for (const bt9 of btn3_3) {
    bt9.style.boxShadow = '2.5px 2.5px 0px #000'
  }

  body.style.background = ' rgb(46,46,46)'
}

if (hour > 18 || hour < 6) {
  background_change_night()
} else {
  background_change_sun()
}
